# not using sudo
sudo: false

language: node_js
node_js:
- '4'

# setup the travis token
env:
  global:
    - secure: IVQXln6SiiMPWZRh+Q7nB4FPrniGMYU7jtwT+tN5WxYvL0lpy0BKvSuN6kZ+j6ka7QkVwZFkttrYHGglwu7VL//rMR9MulXnX8ZqQNlyuXWeaCHUx2kxXQel/33fAh0mT5xlmwdWBHyHhHV6bYGY7iMSgLghBke76F6qh49+MMej9ozP3T/xAuI4Nuih3GHxUvZxnb817JSHwh9xhCPHBdD54XNkUcInAZ1ILSx6dWdyMlBp+MGUGUgLNSP3VKj2/uw5Xy/g+f21JdyfSAiMY2AFv7rzzwK8Dnlhpp7wo6ggX18wa8G/LzftQvAIrNJQ8jeq/dcO186SNujENrOtdZwTqr3bGfwlmOUx0+xAiKE9o+YJo+A8ndjYWFeZs4snm6d3NWscV9QHRdGmNsjjUXnQSMLqMvr4/hMoSp2B+9O5bMLCaiiV7GDJQfSLpFW1+nvTkKpff+JXlmB4dA6+UrZSzJClDqE2/QDLHFqZX2BJX8fhzZ35+/Dp44cxqxvcrTIVGMnEUamIeYmskX/AwYX0UFXCHsG4hq0Jy36h4VPwyd9yUGrmNijuWfaNwfN7jJDKVmbuQOUONo+8LqgoKW2V2wJByAdx/JFvTbUWrlchqGnfny2O5h3gbjGpa9IzLsIDw7MitLrJ9hzCcePDAeiHAGL9GLp/wPkkwUTazDU=

# update gh-pages if all good
after_success:
  - chmod +x ./resources/scripts/update-gh-pages.sh
  - ./resources/scripts/update-gh-pages.sh
